### ISSUE TITLE
Link to "Arduino Runtime for MicroPython" points to "Arduino Modulino" library

### ISSUE THREAD

**Issue by csarnataro** [arduino/package-index-py#36]
I just noticed that the link to "Arduino Runtime for MicroPython" actually points to Arduino library.

I think the offending code is here:

```yaml
  - name: Arduino Runtime for MicroPython
    url: https://github.com/arduino/arduino-modulino-mpy
    author: Arduino, Ubi de Feo, Sebastian Romero
```

https://github.com/arduino/package-index-py/blob/main/package-list.yaml#L286

I will create a PR soon.
